### ISSUE TITLE
C4.5

### ISSUE THREAD

**Issue by audio99** [SCI2SUGR/KEEL#1]
sir, where is the class of decision tree to calculate the entropy, information gain, gain ratio, and cross validation, also confusion matrix?  @SCI2S @dianamartinr @sergiogvz @triguero @JLuengo

**Comment by aFdezHilario** [comment]
Information gain functions are computed within Cut class. 

Cross validation is performed a priori on the main window of the KEEL Software.

Confusion matrix is obtained by a specific "box" / procedure in the experimental section.
