### ISSUE TITLE
Source for implementation of statistical comparisons

### ISSUE THREAD

**Issue by albertiniufu** [SCI2SUGR/KEEL#16]
Could you insert in your documentation the paper/source for you implementation of the statistical comparisons between NxN methods?

**Comment by sergiogvz** [comment]
Hi albertiniufu,

the statistical tests, which are implemented in [here](https://github.com/SCI2SUGR/KEEL/tree/master/src/keel/GraphInterKeel/statistical), are documented in the Reference Manual of [keel.es](http://www.keel.es). Additionally, you can find a Thematic site about these statistical tests with several papers in [https://sci2s.ugr.es/sicidm](https://sci2s.ugr.es/sicidm)
