### ISSUE TITLE
Configuration file !!

### ISSUE THREAD

**Issue by SofienBoutaib** [SCI2SUGR/KEEL#18]
I put all the parameters and the input and output files paths. But when the algorithm reaches this instruction 'ficheroTree = parameters.getOutputFile(0);' in the class DT_oblicuo(). An error appears as follows:
```
Exception in thread "main" java.lang.NullPointerException
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.core.Fichero.escribeFichero(Fichero.java:30)
	at DT_oblicuo.escribeResultados(DT_oblicuo.java:150)
	at DT_oblicuo.execute(DT_oblicuo.java:107)
	at Main.execute(Main.java:18)
	at Main.main(Main.java:36)
```
My configuration file is as follows:
![image](https://user-images.githubusercontent.com/26431595/47708978-97041180-dc2f-11e8-8dc7-26fdedc239c7.png)

**Comment by sergiogvz** [comment]
In your configuration file, an output file is missing in the outputData field. There must be three output files:  training predictions, test predictions and the representation of the decision tree.

This is an example of a configuration file obtained with KEEL 3.0 (2018-04-09):

`algorithm = Evolutionary Oblique DT Induction
inputData = "../datasets/iris/iris-10-1tra.dat" "../datasets/iris/iris-10-1tra.dat" "../datasets/iris/iris-10-1tst.dat" 
outputData = "../results/DT_Oblique-C.iris/result0s0.tra" "../results/DT_Oblique-C.iris/result0s0.tst" "../results/DT_Oblique-C.iris/result0s0e0.txt"  

seed = 1286082570
Number of Total Generations for the GA = 25`

**Comment by SofienBoutaib** [comment]
Okay, thank you.
