### ISSUE TITLE
No existe el archivo GraphInterKeel.jar

### ISSUE THREAD

**Issue by ugarciac** [SCI2SUGR/KEEL#20]
No se puede ejecutar java -jar ./dist/GraphInterKeel.jar ya que el archivo GraphInterKeel.jar no existe en la ruta.

Sistema Operativo: Mac

**Comment by triguero** [comment]
Ulises,

The github repository only contains the source files of the project. As detailed in the README file, you should compile it to get access to that .jar file.

However, you can download a pre-compiled version on the Keel website:

http://sci2s.ugr.es/keel/software/prototypes/openVersion/Software-2018-04-09.zip

Hope that helps,

Isaac
